const order=JSON.parse(localStorage.getItem("kantinku_order")||"null");if(!order){location.href="index.html"}else{
const methods={ewallet:[["gopay","GoPay","Bayar cepat dari aplikasi GoPay","🟢"],["dana","DANA","Praktis untuk pembayaran harian","🔵"],["ovo","OVO","Gunakan saldo OVO kamu","🟣"]],bank:[["bca","BCA","Transfer melalui BCA Mobile / ATM","🔷"],["bri","BRI","Transfer melalui BRImo / ATM","🔵"],["mandiri","Mandiri","Transfer melalui Livin' by Mandiri","🟡"]],qris:[["qris","QRIS","Scan sekali dari e-wallet atau mobile banking","▦"]]};
let selected="gopay";
function renderMethods(group="ewallet"){document.querySelector("#methods").innerHTML=methods[group].map(m=>`<button class="method ${m[0]===selected?"selected":""}" data-id="${m[0]}"><span class="method-icon">${m[3]}</span><span><b>${m[1]}</b><small>${m[2]}</small></span><i>✓</i></button>`).join("");document.querySelectorAll(".method").forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderMethods(group)})}
document.querySelector("#paymentItems").innerHTML=order.cart.map(x=>{const p=PRODUCTS.find(p=>p.id===x.id);return `<div class="payment-item"><span>${p.name} × ${x.qty}</span><b>${money(p.price*x.qty)}</b></div>`}).join("");document.querySelector("#paymentTotal").textContent=money(order.total);document.querySelector("#payAmount").textContent=money(order.total);document.querySelector("#qrAmount").textContent=money(order.total);renderMethods();
document.querySelectorAll(".pay-tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".pay-tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");renderMethods(t.dataset.group)});
document.querySelector("#confirmPay").onclick=()=>{if(selected==="qris"){document.querySelector("#qrModal").classList.add("show")}else completePayment()};
document.querySelector("#closeQR").onclick=()=>document.querySelector("#qrModal").classList.remove("show");document.querySelector("#paidBtn").onclick=completePayment;
function completePayment(){const code="KN-"+Math.floor(100000+Math.random()*900000);localStorage.setItem("kantinku_order_code",code);localStorage.setItem("kantinku_payment",selected);localStorage.removeItem("kantinku_cart");localStorage.removeItem("kantinku_order_draft");location.href="order-status.html"}
}